
GRANT USAGE, CREATE ON SCHEMA "public" TO "danilo_silva";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "public" TO "danilo_silva";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "public" TO "danilo_silva";
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA "public" TO "danilo_silva";
GRANT ALL PRIVILEGES ON ALL ROUTINES IN SCHEMA "public" TO "danilo_silva";
ALTER DEFAULT PRIVILEGES IN SCHEMA "public" GRANT ALL ON TABLES TO "danilo_silva";
ALTER DEFAULT PRIVILEGES IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "danilo_silva";
ALTER DEFAULT PRIVILEGES IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "danilo_silva";
ALTER DEFAULT PRIVILEGES IN SCHEMA "public" GRANT ALL ON ROUTINES TO "danilo_silva";
GRANT SELECT, INSERT, REFERENCES, DELETE, TRIGGER, TRUNCATE, UPDATE 
ON ALL TABLES IN SCHEMA "public"
TO "danilo_silva";

GRANT USAGE, CREATE ON SCHEMA "public" TO "robinson_silva";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "public" TO "robinson_silva";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "public" TO "robinson_silva";
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA "public" TO "robinson_silva";
GRANT ALL PRIVILEGES ON ALL ROUTINES IN SCHEMA "public" TO "robinson_silva";
ALTER DEFAULT PRIVILEGES IN SCHEMA "public" GRANT ALL ON TABLES TO "robinson_silva";
ALTER DEFAULT PRIVILEGES IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "robinson_silva";
ALTER DEFAULT PRIVILEGES IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "robinson_silva";
ALTER DEFAULT PRIVILEGES IN SCHEMA "public" GRANT ALL ON ROUTINES TO "robinson_silva";
GRANT SELECT, INSERT, REFERENCES, DELETE, TRIGGER, TRUNCATE, UPDATE 
ON ALL TABLES IN SCHEMA "public" TO "robinson_silva";

GRANT USAGE, CREATE ON SCHEMA "public" TO "lucas_pratas";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "public" TO "lucas_pratas";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "public" TO "lucas_pratas";
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA "public" TO "lucas_pratas";
GRANT ALL PRIVILEGES ON ALL ROUTINES IN SCHEMA "public" TO "lucas_pratas";
ALTER DEFAULT PRIVILEGES IN SCHEMA "public" GRANT ALL ON TABLES TO "lucas_pratas";
ALTER DEFAULT PRIVILEGES IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "lucas_pratas";
ALTER DEFAULT PRIVILEGES IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "lucas_pratas";
ALTER DEFAULT PRIVILEGES IN SCHEMA "public" GRANT ALL ON ROUTINES TO "lucas_pratas";
GRANT SELECT, INSERT, REFERENCES, DELETE, TRIGGER, TRUNCATE, UPDATE 
ON ALL TABLES IN SCHEMA "public" TO "lucas_pratas";

GRANT USAGE, CREATE ON SCHEMA "public" TO "engine";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "public" TO "engine";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "public" TO "engine";
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA "public" TO "engine";
GRANT ALL PRIVILEGES ON ALL ROUTINES IN SCHEMA "public" TO "engine";
ALTER DEFAULT PRIVILEGES IN SCHEMA "public" GRANT ALL ON TABLES TO "engine";
ALTER DEFAULT PRIVILEGES IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "engine";
ALTER DEFAULT PRIVILEGES IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "engine";
ALTER DEFAULT PRIVILEGES IN SCHEMA "public" GRANT ALL ON ROUTINES TO "engine";
GRANT SELECT, INSERT, REFERENCES, DELETE, TRIGGER, TRUNCATE, UPDATE 
ON ALL TABLES IN SCHEMA "public" TO "engine";


GRANT USAGE, CREATE ON SCHEMA "public" TO "gabriel_sifuentes";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "public" TO "gabriel_sifuentes";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "public" TO "gabriel_sifuentes";
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA "public" TO "gabriel_sifuentes";
GRANT ALL PRIVILEGES ON ALL ROUTINES IN SCHEMA "public" TO "gabriel_sifuentes";
ALTER DEFAULT PRIVILEGES IN SCHEMA "public" GRANT ALL ON TABLES TO "gabriel_sifuentes";
ALTER DEFAULT PRIVILEGES IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "gabriel_sifuentes";
ALTER DEFAULT PRIVILEGES IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "gabriel_sifuentes";
ALTER DEFAULT PRIVILEGES IN SCHEMA "public" GRANT ALL ON ROUTINES TO "gabriel_sifuentes";
GRANT SELECT, INSERT, REFERENCES, DELETE, TRIGGER, TRUNCATE, UPDATE 
ON ALL TABLES IN SCHEMA "public" TO "gabriel_sifuentes";


-- GRANT ALL ON SCHEMA public TO engine, robinson_silva, danilo_silva, lucas_pratas, gabriel_sifuentes;

-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO  engine, robinson_silva, danilo_silva, lucas_pratas, gabriel_sifuentes;
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO  engine, robinson_silva, danilo_silva, lucas_pratas, gabriel_sifuentes;

-- ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO  engine, robinson_silva, danilo_silva, lucas_pratas, gabriel_sifuentes;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO  engine, robinson_silva, danilo_silva, lucas_pratas, gabriel_sifuentes;


